package com.islandblast.game.level6

import android.content.res.AssetManager
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Typeface
import com.islandblast.game.model.Box
import org.json.JSONArray
import org.json.JSONObject

/** Level 6 layout, generated by tools/level6/build6.py as assets/level6/level6.json. */
class StormSpec(json: String) {
    private val o = JSONObject(json)
    val stageW: Float
    val stageH: Float
    val skyMarginX: Float
    val skyMarginY: Float
    val horizon: Float
    val playerY: Float
    val vanishX: Float
    val laneW: Float
    val depth: Float
    val sprites: Map<String, Box>
    val pause: Box
    val stars: List<Box>
    val arrowLeft: FloatArray
    val arrowRight: FloatArray
    val hudExtent: Box
    val scoreX: Float
    val scoreY: Float
    val scoreSize: Float
    val timerX: Float
    val timerY: Float
    val timerSize: Float

    init {
        val st = o.getJSONArray("stage")
        stageW = st.getDouble(0).toFloat(); stageH = st.getDouble(1).toFloat()
        val sky = o.getJSONObject("sky").getJSONArray("margin")
        skyMarginX = sky.getDouble(0).toFloat(); skyMarginY = sky.getDouble(1).toFloat()
        val p = o.getJSONObject("perspective")
        horizon = p.f("horizon"); playerY = p.f("playerY"); vanishX = p.f("vanishX")
        laneW = p.f("laneW"); depth = p.f("depth")
        val sp = o.getJSONObject("sprites")
        sprites = sp.keys().asSequence().associateWith { sp.getJSONObject(it).getJSONArray("box").box() }
        val h = o.getJSONObject("hud")
        pause = h.getJSONArray("pause").box()
        stars = (0 until h.getJSONArray("stars").length()).map { h.getJSONArray("stars").getJSONArray(it).box() }
        arrowLeft = h.getJSONArray("arrowLeft").floats()
        arrowRight = h.getJSONArray("arrowRight").floats()
        hudExtent = h.getJSONArray("extent").box()
        val s = h.getJSONObject("scoreText"); scoreX = s.f("x"); scoreY = s.f("y"); scoreSize = s.f("size")
        val t = h.getJSONObject("timerText"); timerX = t.f("x"); timerY = t.f("y"); timerSize = t.f("size")
    }

    /** Perspective scale of a point [dz] river units ahead of the jet ski (1 at the ski). */
    fun scaleAt(dz: Float) = depth / (depth + dz)
    fun yAt(dz: Float) = horizon + (playerY - horizon) * scaleAt(dz)
    fun xAt(lanes: Float, dz: Float) = vanishX + lanes * laneW * scaleAt(dz)

    private fun JSONObject.f(k: String) = getDouble(k).toFloat()
    private fun JSONArray.box() = Box(getDouble(0).toFloat(), getDouble(1).toFloat(), getDouble(2).toFloat(), getDouble(3).toFloat())
    private fun JSONArray.floats() = FloatArray(length()) { getDouble(it).toFloat() }
}

class StormAssets(private val am: AssetManager) {
    val spec = StormSpec(am.open("$DIR/level6.json").bufferedReader().use { it.readText() })

    private val opts = BitmapFactory.Options().apply {
        inScaled = false
        inPreferredConfig = Bitmap.Config.ARGB_8888
    }

    private fun bmp(name: String): Bitmap =
        (am.open("$DIR/$name").use { BitmapFactory.decodeStream(it, null, opts) } ?: error("Missing asset $name"))
            .apply { density = Bitmap.DENSITY_NONE }

    val sky = bmp("sky.png")
    val water = bmp("water.png")
    val sprite: Map<String, Bitmap> = listOf(
        "barrel", "barrel_open", "barrel_small", "mine", "crate_x", "logs", "plank", "coin", "coin_side",
        "shield", "x_hazard", "jetski", "arrow_left", "arrow_right", "leaves", "star_gold", "star_empty",
    ).associateWith { bmp("$it.png") }

    val skyBlur: Bitmap = Bitmap.createScaledBitmap(Bitmap.createScaledBitmap(sky, 64, 50, true), 16, 12, true)

    val fredoka: Typeface = Typeface.createFromAsset(am, "fonts/Fredoka-Bold.ttf")

    companion object {
        const val DIR = "level6"
    }
}
