package com.islandblast.game.temple

import android.content.res.AssetManager
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Typeface
import com.islandblast.game.model.Box
import org.json.JSONArray
import org.json.JSONObject

/** A live HUD string placed where the approved screen paints it (left-baseline anchor). */
class TextSpot(val x: Float, val y: Float, val size: Float)

/** Side scenery cut from the painting: where it stands ([x] lanes across, [z] ahead) and its size. */
class PropSpec(val name: String, val box: Box, val side: Int, val x: Float, val z: Float, val w: Float, val h: Float)

/** Level 5 (Temple Chase) layout, generated by tools/temple/build_temple.py as assets/temple/temple.json. */
class TempleSpec(json: String) {
    private val o = JSONObject(json)
    val stageW: Float
    val stageH: Float
    val marginX: Float
    val marginY: Float
    val horizon: Float
    val playerY: Float
    val vanishX: Float
    val laneW: Float
    val depth: Float
    val camBias: Float
    val groundZ0: Float
    val introK: Float
    val introHalf: Float
    val pathK: Float
    val pathHalf: Float
    val pathPeriod: Float
    val lavaX: Float
    val lavaZ: Float
    val props: List<PropSpec>
    val sprites: Map<String, Box>
    val pause: Box
    val hearts: List<Box>
    val stars: List<Box>
    val arrowLeft: FloatArray
    val arrowRight: FloatArray
    /** Power-up buttons: lightning, shield, magnet — disc (cx, cy, r) and count badge (cx, cy, r). */
    val powerDiscs: List<FloatArray>
    val powerBadges: List<FloatArray>
    val hudExtent: Box
    val scoreText: TextSpot
    val coinText: TextSpot
    val timerText: TextSpot
    val countSize: Float
    val countDx: Float
    val countDy: Float

    init {
        val st = o.getJSONArray("stage")
        stageW = st.getDouble(0).toFloat(); stageH = st.getDouble(1).toFloat()
        val m = o.getJSONObject("backdrop").getJSONArray("margin")
        marginX = m.getDouble(0).toFloat(); marginY = m.getDouble(1).toFloat()
        val p = o.getJSONObject("perspective")
        horizon = p.f("horizon"); playerY = p.f("playerY"); vanishX = p.f("vanishX")
        laneW = p.f("laneW"); depth = p.f("depth"); camBias = p.f("camBias")
        val g = o.getJSONObject("ground")
        groundZ0 = g.f("z0"); introK = g.f("introK"); introHalf = g.f("introHalf")
        pathK = g.f("pathK"); pathHalf = g.f("pathHalf"); pathPeriod = g.f("pathPeriod")
        lavaX = g.f("lavaX"); lavaZ = g.f("lavaZ")
        val pr = o.getJSONObject("props")
        props = pr.keys().asSequence().map { k ->
            val q = pr.getJSONObject(k)
            PropSpec(k, q.getJSONArray("box").box(), q.getInt("side"), q.f("x"), q.f("z"), q.f("w"), q.f("h"))
        }.toList()
        val sp = o.getJSONObject("sprites")
        sprites = sp.keys().asSequence().associateWith { sp.getJSONObject(it).getJSONArray("box").box() }
        powerDiscs = listOf("pu_lightning", "pu_shield", "pu_magnet").map { sp.getJSONObject(it).getJSONArray("centre").floats() }
        powerBadges = listOf("pu_lightning", "pu_shield", "pu_magnet").map { sp.getJSONObject(it).getJSONArray("badge").floats() }
        val h = o.getJSONObject("hud")
        pause = h.getJSONArray("pause").box()
        hearts = h.getJSONArray("hearts").let { a -> (0 until a.length()).map { a.getJSONArray(it).box() } }
        stars = h.getJSONArray("stars").let { a -> (0 until a.length()).map { a.getJSONArray(it).box() } }
        arrowLeft = h.getJSONArray("arrowLeft").floats()
        arrowRight = h.getJSONArray("arrowRight").floats()
        hudExtent = h.getJSONArray("extent").box()
        val t = h.getJSONObject("text")
        scoreText = t.getJSONObject("score").spot()
        coinText = t.getJSONObject("coins").spot()
        timerText = t.getJSONObject("timer").spot()
        val c = t.getJSONObject("count")
        countSize = c.f("size"); countDx = c.f("dx"); countDy = c.f("dy")
    }

    /** Perspective scale of a point [dz] units ahead of the runner (1 at the runner). */
    fun scaleAt(dz: Float) = depth / (depth + dz)
    fun yAt(dz: Float) = horizon + (playerY - horizon) * scaleAt(dz)

    /** Screen x of a point [lanes] across the path, [dz] ahead, seen from a camera [cam] lanes across. */
    fun xAt(lanes: Float, dz: Float, cam: Float) = vanishX + (lanes - cam) * laneW * scaleAt(dz)

    /** Lateral position (lanes) under screen x at the runner's depth. */
    fun lanesAtRunner(x: Float, cam: Float) = (x - vanishX) / laneW + cam

    private fun JSONObject.f(k: String) = getDouble(k).toFloat()
    private fun JSONObject.spot() = TextSpot(f("x"), f("y"), f("size"))
    private fun JSONArray.box() = Box(getDouble(0).toFloat(), getDouble(1).toFloat(), getDouble(2).toFloat(), getDouble(3).toFloat())
    private fun JSONArray.floats() = FloatArray(length()) { getDouble(it).toFloat() }
}

class TempleAssets(private val am: AssetManager) {
    val spec = TempleSpec(am.open("$DIR/temple.json").bufferedReader().use { it.readText() })

    private val opts = BitmapFactory.Options().apply {
        inScaled = false
        inPreferredConfig = Bitmap.Config.ARGB_8888
    }

    private fun bmp(name: String): Bitmap =
        (am.open("$DIR/$name").use { BitmapFactory.decodeStream(it, null, opts) } ?: error("Missing asset $name"))
            .apply { density = Bitmap.DENSITY_NONE }

    val backdrop = bmp("backdrop.png")
    val path = bmp("path.png")
    val lava = bmp("lava.jpg")
    val introGround = bmp("ground_intro.png")
    val props: Map<String, Bitmap> = spec.props.associate { it.name to bmp("prop_${it.name}.png") }
    val sprite: Map<String, Bitmap> = listOf(
        "runner", "coin", "gem", "boulder", "arrow_left", "arrow_right", "pu_lightning", "pu_shield", "pu_magnet",
        "heart", "heart_empty", "star_gold", "star_empty",
    ).associateWith { bmp("$it.png") }

    val backdropBlur: Bitmap = Bitmap.createScaledBitmap(Bitmap.createScaledBitmap(backdrop, 64, 66, true), 16, 16, true)
    val fredoka: Typeface = Typeface.createFromAsset(am, "fonts/Fredoka-Bold.ttf")

    companion object {
        const val DIR = "temple"
    }
}
