package com.islandblast.game.model

import org.json.JSONArray
import org.json.JSONObject

enum class TargetKind { GEM, COIN, BARREL, CRATE, CHEST }

/** One hovering treasure, cut from the approved Level 4 screen. */
class TargetSpec(
    val id: String,
    val kind: TargetKind,
    /** Where its sprite sits at rest (stage units). */
    val box: Box,
    val cx: Float,
    val cy: Float,
    /** Radius of a circle with the same area: its size for scoring and effects. */
    val radius: Float,
    /** Convex outline (x0, y0, x1, y1, ...) at rest: the shape the bolt must touch. */
    val hull: FloatArray,
)

class Hud4(
    val pause: Box,
    val stars: List<Box>,
    /** Inside of the time bar; the fill runs from its left edge. */
    val timeBarTrack: Box,
    /** The painted fill (0:28 left), whose sprite is drawn 3-slice at any length. */
    val timeBarFill: Box,
    val comboBox: Box,
    /** Everything that must stay inside the phone's safe area. */
    val extent: Box,
    val timer: TextSpot,
    val score: TextSpot,
    val combo: TextSpot,
    val comboNumber: TextSpot,
)

/**
 * Level 4 "Mystic Harvest" layout, generated by tools/level4/build.py from the
 * approved screen and shipped as assets/level4/level4.json.
 */
class Level4Spec(
    val stageW: Float,
    val stageH: Float,
    val extMarginX: Float,
    val extMarginY: Float,
    val targets: List<TargetSpec>,
    val launcherBox: Box,
    val pivotX: Float,
    val pivotY: Float,
    val tipX: Float,
    val tipY: Float,
    /** The opening frame's burst: fx_glow/fx_debris sit in this box. */
    val introBox: Box,
    val introPieces: List<IntroPiece>,
    val burstX: Float,
    val burstY: Float,
    val hud: Hud4,
) {
    companion object {
        fun parse(json: String): Level4Spec {
            val o = JSONObject(json)
            val stage = o.getJSONArray("stage")
            val ext = o.getJSONObject("backgroundExt").getJSONArray("margin")
            val targets = o.getJSONArray("targets").objects().map { t ->
                val c = t.getJSONArray("center")
                val hull = t.getJSONArray("hull").arrays()
                TargetSpec(
                    id = t.getString("id"),
                    kind = TargetKind.valueOf(t.getString("kind").uppercase()),
                    box = t.getJSONArray("box").box(),
                    cx = c.f(0), cy = c.f(1),
                    radius = t.getDouble("radius").toFloat(),
                    hull = FloatArray(hull.size * 2) { i -> hull[i / 2].f(i % 2) },
                )
            }
            val l = o.getJSONObject("launcher")
            val intro = o.getJSONObject("intro")
            val burst = intro.getJSONArray("burstCenter")
            val pieces = intro.getJSONArray("pieces").objects().map { p ->
                val c = p.getJSONArray("center")
                IntroPiece("debris", p.getJSONArray("rect").box(), c.f(0), c.f(1))
            }
            val h = o.getJSONObject("hud")
            val text = h.getJSONObject("text")
            return Level4Spec(
                stageW = stage.f(0), stageH = stage.f(1),
                extMarginX = ext.f(0), extMarginY = ext.f(1),
                targets = targets,
                launcherBox = l.getJSONArray("box").box(),
                pivotX = l.getJSONArray("pivot").f(0), pivotY = l.getJSONArray("pivot").f(1),
                tipX = l.getJSONArray("tip").f(0), tipY = l.getJSONArray("tip").f(1),
                introBox = intro.getJSONArray("box").box(),
                introPieces = pieces,
                burstX = burst.f(0), burstY = burst.f(1),
                hud = Hud4(
                    pause = h.getJSONArray("pause").box(),
                    stars = h.getJSONArray("stars").arrays().map { it.box() },
                    timeBarTrack = h.getJSONArray("timeBarTrack").box(),
                    timeBarFill = h.getJSONArray("timeBarFill").box(),
                    comboBox = h.getJSONArray("comboBox").box(),
                    extent = h.getJSONArray("extent").box(),
                    timer = text.getJSONObject("timer").spot(),
                    score = text.getJSONObject("score").spot(),
                    combo = text.getJSONObject("combo").spot(),
                    comboNumber = text.getJSONObject("comboNumber").spot(),
                ),
            )
        }

        private fun JSONArray.f(i: Int) = getDouble(i).toFloat()
        private fun JSONObject.f(key: String) = getDouble(key).toFloat()
        private fun JSONObject.spot() = TextSpot(f("x"), f("y"), f("size"), f("angle"), f("scaleX"), f("width"))
        private fun JSONArray.box() = Box(f(0), f(1), f(2), f(3))
        private fun JSONArray.objects() = (0 until length()).map { getJSONObject(it) }
        private fun JSONArray.arrays() = (0 until length()).map { getJSONArray(it) }
    }
}
