package com.islandblast.game.model

import org.json.JSONArray
import org.json.JSONObject

/** Axis-aligned box in stage units (the 1024x1536 reference canvas). */
data class Box(val l: Float, val t: Float, val r: Float, val b: Float) {
    val w get() = r - l
    val h get() = b - t
    val cx get() = (l + r) / 2f
    val cy get() = (t + b) / 2f
}

data class BlockSpec(
    val id: String,
    val rect: Box,
    /** Rects of the block art this block owns (its rect minus blocks drawn in front of it). */
    val parts: List<Box>,
    /** Colour as painted in the approved reference (may be an in-between hue). */
    val art: String,
    /** Colour the game treats it as at the start of the level. */
    val color: GameColor,
    /** Painted hue sits between two game colours; eased to the game colour after the intro. */
    val normalize: Boolean,
)

data class IntroPiece(val kind: String, val rect: Box, val cx: Float, val cy: Float)

/**
 * Level 5 layout, generated by tools/assets/build_sprites.py from the approved
 * reference and shipped as assets/level5/level5.json.
 */
class LevelSpec(
    val stageW: Float,
    val stageH: Float,
    val atlasX: Float,
    val atlasY: Float,
    val blocks: List<BlockSpec>,
    val introPieces: List<IntroPiece>,
    val shardSizes: List<Pair<Int, Int>>,
    val ballX: Float,
    val ballY: Float,
    val ballRadius: Float,
    val ballSpriteBox: Box,
    val chevronW: Float,
    val chevronH: Float,
    val chevronPad: Float,
    val chevronScale: Float,
    val flashX: Float,
    val flashY: Float,
    val flashRadius: Float,
    val starBoxes: List<Box>,
    /** Aim chevrons as painted for the straight-up shot: (distance from ball centre, width). */
    val chevronTrack: List<Pair<Float, Float>>,
) {
    companion object {
        fun parse(json: String): LevelSpec {
            val o = JSONObject(json)
            val stage = o.getJSONArray("stage")
            val origin = o.getJSONArray("atlasOrigin")
            val blocks = o.getJSONArray("blocks").objects().map { b ->
                BlockSpec(
                    id = b.getString("id"),
                    rect = b.getJSONArray("rect").box(),
                    parts = b.getJSONArray("parts").arrays().map { it.box() },
                    art = b.getString("art"),
                    color = GameColor.of(b.getString("color")),
                    normalize = b.getBoolean("normalize"),
                )
            }
            val pieces = o.getJSONArray("introPieces").objects().map { p ->
                val c = p.getJSONArray("center")
                IntroPiece(p.getString("kind"), p.getJSONArray("rect").box(),
                    c.getDouble(0).toFloat(), c.getDouble(1).toFloat())
            }
            val shards = o.getJSONArray("shards").arrays().map { it.getInt(0) to it.getInt(1) }
            val ball = o.getJSONObject("ball")
            val ballC = ball.getJSONArray("center")
            val chev = o.getJSONObject("chevron")
            val flash = o.getJSONObject("flash")
            val flashC = flash.getJSONArray("center")
            return LevelSpec(
                stageW = stage.getDouble(0).toFloat(),
                stageH = stage.getDouble(1).toFloat(),
                atlasX = origin.getDouble(0).toFloat(),
                atlasY = origin.getDouble(1).toFloat(),
                blocks = blocks,
                introPieces = pieces,
                shardSizes = shards,
                ballX = ballC.getDouble(0).toFloat(),
                ballY = ballC.getDouble(1).toFloat(),
                ballRadius = ball.getDouble("radius").toFloat(),
                ballSpriteBox = ball.getJSONArray("spriteBox").box(),
                chevronW = chev.getJSONArray("size").getDouble(0).toFloat(),
                chevronH = chev.getJSONArray("size").getDouble(1).toFloat(),
                chevronPad = chev.getDouble("pad").toFloat(),
                chevronScale = chev.getDouble("scale").toFloat(),
                flashX = flashC.getDouble(0).toFloat(),
                flashY = flashC.getDouble(1).toFloat(),
                flashRadius = flash.getDouble("radius").toFloat(),
                starBoxes = o.getJSONArray("stars").arrays().map { it.box() },
                chevronTrack = chev.getJSONArray("track").arrays()
                    .map { it.getDouble(0).toFloat() to it.getDouble(1).toFloat() },
            )
        }

        private fun JSONArray.box() = Box(
            getDouble(0).toFloat(), getDouble(1).toFloat(),
            getDouble(2).toFloat(), getDouble(3).toFloat(),
        )

        private fun JSONArray.objects() = (0 until length()).map { getJSONObject(it) }
        private fun JSONArray.arrays() = (0 until length()).map { getJSONArray(it) }
    }
}
